modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "betteradvancedtooltips"
version = "${version}"
displayName = "Better Advanced Tooltips"
description = "Adds tag, component and other tooltips to items in F3+H mode"
authors = "latvian.dev"
logoFile = "betteradvancedtooltips_logo.png"
logoBlur = false

[[dependencies.betteradvancedtooltips]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.199,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "betteradvancedtooltips.mixins.json"